-- MySQL Script generated by MySQL Workbench
-- Fri Jan  1 12:32:55 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema farmacia
-- -----------------------------------------------------
-- Base de datos para venta de productos farmaceuticos en forma presencial y por medio de call center
DROP SCHEMA IF EXISTS `farmacia` ;

-- -----------------------------------------------------
-- Schema farmacia
--
-- Base de datos para venta de productos farmaceuticos en forma presencial y por medio de call center
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `farmacia` DEFAULT CHARACTER SET utf8 ;
USE `farmacia` ;

-- -----------------------------------------------------
-- Table `farmacia`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farmacia`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `farmacia`.`Cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`Proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farmacia`.`Proveedor` ;

CREATE TABLE IF NOT EXISTS `farmacia`.`Proveedor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`Medicina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farmacia`.`Medicina` ;

CREATE TABLE IF NOT EXISTS `farmacia`.`Medicina` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(500) NULL,
  `cantidad` INT NOT NULL,
  `precio` DECIMAL(9,2) NOT NULL,
  `proveedor_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_medicina_proveedor_idx` (`proveedor_id` ASC),
  CONSTRAINT `fk_medicina_proveedor`
    FOREIGN KEY (`proveedor_id`)
    REFERENCES `farmacia`.`Proveedor` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`PuntoVenta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farmacia`.`PuntoVenta` ;

CREATE TABLE IF NOT EXISTS `farmacia`.`PuntoVenta` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'El punto de venta puede ser call center o agencia para comprar de forma presencial',
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `telefonos` VARCHAR(45) NULL,
  `latitud` VARCHAR(45) NULL,
  `logitud` VARCHAR(45) NULL,
  `tipo_punto_venta` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`Empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farmacia`.`Empleado` ;

CREATE TABLE IF NOT EXISTS `farmacia`.`Empleado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `tipo_empleado` VARCHAR(45) NOT NULL,
  `punto_venta_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_empleado_punto_venta1_idx` (`punto_venta_id` ASC),
  CONSTRAINT `fk_empleado_punto_venta1`
    FOREIGN KEY (`punto_venta_id`)
    REFERENCES `farmacia`.`PuntoVenta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farmacia`.`Pedido` ;

CREATE TABLE IF NOT EXISTS `farmacia`.`Pedido` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NULL,
  `hora_salida` DATETIME NULL,
  `hora_entrega` VARCHAR(45) NULL,
  `direccion_entrega` VARCHAR(250) NULL,
  `nombre_recibe` VARCHAR(45) NULL,
  `total` INT NULL,
  `repartidor` VARCHAR(45) NULL,
  `call_center` VARCHAR(45) NULL,
  `creado_por` VARCHAR(45) NULL,
  `gestionado_por` VARCHAR(45) NULL,
  `cliente` VARCHAR(45) NULL,
  `tipo_pago` VARCHAR(45) NULL,
  `recargo` INT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`DetallePedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farmacia`.`DetallePedido` ;

CREATE TABLE IF NOT EXISTS `farmacia`.`DetallePedido` (
  `pedido_id` INT NOT NULL,
  `medicina` VARCHAR(100) NOT NULL,
  `cantidad` INT NOT NULL,
  `subtotal` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  INDEX `fk_DetallePedido_Pedido1_idx` (`pedido_id` ASC),
  CONSTRAINT `fk_DetallePedido_Pedido1`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `farmacia`.`Pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
